config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :scans
  map.resources :vulnerabilities
  map.resources :hosts
  map.resources :plugins
  map.resources :severities
  map.resources :locations
  map.resources :plugin_classifications
  map.resources :classifications
  map.root :controller => 'Scans'
end

app/models/scan.rb
class Scan < ActiveRecord::Base
  has_many :hosts
  has_and_belongs_to_many :locations, :uniq => true

  acts_as_state_machine :initial => :waiting

  state :waiting
  state :running
  state :finished

  event :start do
    transitions :to => :running, :from => :waiting
  end

  event :stop do
    transitions :to => :finished, :from => :running
  end

  def puts(str)
    $stderr.puts str
    if self.output
      self.output << str + "\n"
    else
      self.output = str + "\n"
    end
    self.save!
  end

  def location_names
    if locations.empty?
      "Unknown"
    else
      locations.join(", ")
    end
  end

  def subnets
    locations.map(&:subnets).flatten.uniq
  end

  def to_s
    read_attribute(:name)
  end

  def self.choices
    find(:all).map { |scan| [scan.name, scan.id.to_s] }
  end

  def self.run!
    scan = Scan.find_in_state(:first, :waiting, :order => 'starts_at')

    return unless scan && Time.now >= scan.starts_at

    scan.start!

    subnets         = scan.subnets.map(&:cidr).join(' ')
    cur_time        = Time.now
    nmap_results    = File.expand_path(cur_time.strftime(AppConfig.nmap_results_path))
    nessus_results  = File.expand_path(cur_time.strftime(AppConfig.nessus_results_path))
    nessus_plugins  = File.expand_path(cur_time.strftime(AppConfig.nessus_plugins_path))

    FileUtils.mkdir_p(File.dirname(nmap_results))
    FileUtils.mkdir_p(File.dirname(nessus_results))
    FileUtils.mkdir_p(File.dirname(nessus_plugins))

    scan.puts("Finding live hosts in #{subnets}...")
    `#{AppConfig.nmap_path} -n -sP -PE -PT -PM #{subnets} | grep -i "appears to be up" | cut -d" " -f2 > #{nmap_results}`
    scan.puts("Nmap results saved to #{nmap_results}")

    scan.puts("Scanning live hosts in #{subnets}...")
    `#{AppConfig.nessus_path} -T nessus #{nmap_results} #{nessus_results}`
    scan.puts("Nessus results saved to #{nessus_results}")

    scan.puts("Retrieving plugins from Nessus...")
    `#{AppConfig.nessus_path} -p > #{nessus_plugins}`
    scan.puts("Nessus plugins saved to #{nessus_plugins}")

    Nessus.process(scan, nessus_results, nessus_plugins)

    scan.stop!
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  def index
    @scans = Scan.find(:all,
                       :include => [:locations],
                       :page => {:current => params[:page], :size => session[:user].page_size},
                       :order => 'scans.starts_at ASC')
  end

  def show
    @scan = Scan.find(params[:id],
                      :include => [:locations])

    @hosts = Host.find_all_by_scan_id(@scan.id,
                                      :page => { :current => params[:page], :size => session[:user].page_size},
                                      :conditions => {:location_id => session[:user].locations},
                                      :include => [:location])
  end

  def new
    @scan       = Scan.new

    @locations  = Location.find(:all,
                                :conditions => {:id => session[:user].locations})
  end

  def create
    params[:scan][:starts_at] = Chronic.parse(params[:scan][:starts_at])

    @scan = Scan.new(params[:scan])

    respond_to do |format|
      if @scan.save
        flash[:notice] = 'Scan was successfully created.'
        format.html { redirect_to(@scan) }
      else
        flash[:error] = 'Failed to create scan. Please try again.'
        format.html { render :action => :new }
      end
    end
  end
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/scans/_list.html.haml
%table
  %thead
    %tr
      %th{:width => '20%'}= 'Name'
      %th{:width => '45%'}= 'Locations'
      %th{:width => '20%'}= 'Starts At'
      %th{:width => '10%'}= 'State'

  - if scans.respond_to?(:page)
    %tfoot
      %tr
        %th{:colspan => 4}= paginating_links(scans, :window_size => 3)

  %tbody
    - if scans.size == 0
      %tr
        %td{:colspan => 4}= '&nbsp;'

    -for scan in scans
      %tr
        %td= scan.name
        %td= scan.location_names
        %td= scan.starts_at
        %td= scan.state.capitalize
        %td= link_to('Show', scan)

app/views/scans/index.html.haml
= section_for(@scans, :header => 'Scans') do
  = render(:partial => 'scans/list', :locals => { :scans => @scans })

  .footer= link_to('Add Scan', new_scan_path)

app/views/scans/new.html.haml
= section_for(@scan) do
  - form_for(@scan) do |f|
    %dl
      = form_field('Name', f.text_field(:name))
      = form_field('Start At', f.text_field(:starts_at))

      %dt
        %div= 'Locations'
      %dd
        %ul
          - for location in @locations
            %li
              = check_box_tag('scan[location_ids][]', location.id, (@scan.locations.include?(location)))
              = location

    = f.submit('Create')

app/views/scans/show.html.haml
= section_for(@scan) do
  %dl
    = form_field('Starts At', @scan.starts_at)
    = form_field('Last Updated', @scan.updated_at)
    = form_field('State', @scan.state.capitalize)
    = form_field('Locations', @scan.location_names)
    = form_field('Output', "<pre>#{@scan.output}</pre>") if @scan.running? || @scan.finished?

-if @scan.finished?
  = section_for(@hosts, :header => 'Hosts') do
    = render(:partial => 'hosts/list', :locals => { :hosts => @hosts })